name: Release
run-name: Test Close MileStone
on:
  milestone:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release
      
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        tag_name: v1.0.0
      with:
        release_name: Release ${{ env.GITHUB_SHA }}
        draft: false
        prerelease: false
