name: Release
run-name: Test Close MileStone
on:
  milestone:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create release
      run: gh create release ${{ github.event.milestone.title }}
    - name: install yq
      uses: chrisdickinson/setup-yq@latest
    - name: display yq result
      run: echo $(yq .deploy.frontend ./deploy/deploy.yml)

    - name: upload file
      env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: gh release upload ${{ github.event.milestone.title }} release.yml
