name: Release
run-name: Test Close MileStone
on:
  milestone:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create release
      env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: gh release create ${{ github.event.milestone.title }}
    - name: Install yq
      id: setup-yq
      uses: shiipou/setup-yq-action@v2.2.0
      
    - name: display yq result
        echo "VERSION_SHA=$(yq .deploy.backend ./deploy/deploy.yml)"
    - name: Test
        echo $VERSION_SHA
#     - name: Install oci-cli
#       uses: bytesbay/oci-cli-action@v1.0.2
#       with:
#         user: "${{ secrets.OCI_USER }}"
#         fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
#         tenancy: "${{ secrets.OCI_TENANCY }}"
#         region: "${{ secrets.OCI_REGION }}"
#         api_key: |
#           ${{ secrets.OCI_API_KEY }}
        
#     - name: Download oci file
#       run: oci os object bulk-download -bn ${{ secrets.PROJECT_NAME }} --download-dir . --prefix ${{VERSION_SHA}}.jar
      
#     - name: display file
#       env:
#             GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
#       run: gh release upload ${{ github.event.milestone.title }} ${{VERSION_SHA}}.jar
