name: Release
run-name: Test Close MileStone
on:
  milestone:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        tag_name: v1.0.${{ env.GITHUB_SHA }}
        release_name: Release v1.0.${{ env.GITHUB_SHA }}
        draft: false
        prerelease: false
